### ISSUE TITLE
How to import npm module such as moment.js?

### ISSUE THREAD

**Issue by babyjazz** [yogthos/reagent-serverside#1]
I've tried :npm-deps {:moment "2.24.0}  but not work

**Comment by yogthos** [comment]
Unfortunately, `:npm-deps` doesn't actually work with a lot of the dependencies from NPM because there is no standard practice for packaging libraries. The library API has to be in style supported by Google Closure compiler. I would recommend using [shadow-cljs](https://shadow-cljs.github.io/docs/UsersGuide.html) to work with NPM modules.
